daqFlask/main/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired


class LocationForm(FlaskForm):

    StartDate = DateField('Start:', format='%Y-%m-%d',
                          validators=[DataRequired()])
    EndDate = DateField('End:', format='%Y-%m-%d',
                        validators=[DataRequired()])
    HD_checkbox = BooleanField('Heat Deficit On')
    SP_checkbox = BooleanField('Generate Separate Plots')
    SM_checkbox = BooleanField('Smithfield')
    BV_checkbox = BooleanField('Bountiful')
    RP_checkbox = BooleanField('Rose Park')
    LN_checkbox = BooleanField('Lindon')
    submit = SubmitField('Submit')

daqFlask/__init__.py
from flask import Flask
from flask_mail import Mail
from daqFlask.config import Config

# For creating session IDs
from datetime import datetime


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    from daqFlask.main.routes import main
    from daqFlask.errors.handlers import errors

    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

daqFlask/main/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, session, flash, send_file, current_app
from daqFlask.main.forms import LocationForm
from daqFlask.scripts.generator import generator
from datetime import datetime, timedelta

import os
import shutil
from shutil import copyfile

import io
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

main = Blueprint('main', __name__)


def initiate_directory(directory):
    if not os.path.exists(directory):
        os.mkdir(directory)


@main.context_processor
def inject_now():
    return {'now': datetime.utcnow()}


@main.route("/getzip")
def get_zip():
    root_path = os.path.dirname(current_app.instance_path) + '/'
    static_dir = os.path.join(root_path, 'daqFlask/static/')
    data_dir = os.path.join(root_path, 'data/')

    user = session.get('user', None)

    holder_dir = os.path.join(data_dir, 'holder/')
    user_dir = os.path.join(holder_dir, user)

    bdays_file = os.path.join(data_dir, 'daytype/forecast.action.log.csv')

    newPath = shutil.copy(bdays_file, user_dir)

    zip_dest = os.path.join(static_dir, 'downloads/')

    initiate_directory(zip_dest)

    zip_file = zip_dest + 'AirData' + user

    shutil.make_archive(root_dir=user_dir,
                        format='zip', base_name=zip_file)

    zip_file = zip_file + '.zip'

    return send_file(zip_file,
                     mimetype='zip',
                     attachment_filename='AirData.zip',
                     as_attachment=True)


@main.route("/", methods=['GET', 'POST'])
@main.route("/home", methods=['GET', 'POST'])
def home():

    root_path = os.path.dirname(current_app.instance_path) + '/'

    form = LocationForm()

    if form.validate_on_submit():

        stationlist = []

        request.form.getlist("")

        time = datetime.now().strftime('%M%S%f')[:-4]
        todaysdate = datetime.now().strftime("%Y-%m-%d")

        if(form.BV_checkbox.data):
            stationlist.append('bv')

        if(form.LN_checkbox.data):
            stationlist.append('ln')

        if(form.SM_checkbox.data):
            stationlist.append('sm')

        if(form.HD_checkbox.data):
            HD_indicator = True
        else:
            HD_indicator = False

        if(form.SP_checkbox.data):
            SP_indicator = True
        else:
            SP_indicator = False

        time = datetime.now().strftime('%M%S%f')[:-4]
        todaysdate = datetime.now().strftime("%Y-%m-%d")

        startDate = form.StartDate.data
        endDate = form.EndDate.data

        startDate = startDate.strftime('%Y-%m-%d')
        endDate = endDate.strftime('%Y-%m-%d')

        edge_date = '2017-07-18'

        user = todaysdate + time
        session['user'] = user

        if (todaysdate <= startDate):
            flash('Start date must be before today', 'warning')
            return render_template('home.html', form=form)

        if (todaysdate < endDate):
            flash('End date cannot be after today', 'warning')
            return render_template('home.html', form=form)

        if (endDate <= startDate):
            flash('Start date must be before end date', 'warning')
            return render_template('home.html', form=form)

        if not stationlist == []:
            if (startDate < edge_date):
                flash(
                    '07/18/2017 is the earliest date for delta-carbon data.', 'warning')
                return render_template('home.html', form=form)

        if (stationlist == []):

            if(HD_indicator):
                file_names = generator(
                    startDate, endDate, stationlist, user, HD_indicator, SP_indicator, root_path)
                session['id'] = file_names
                return redirect(url_for('main.display', startDate=startDate, endDate=endDate))
            else:
                flash(
                    "You must select at least one location, or heat-deficit", "warning")
                form = LocationForm()
                return render_template('home.html', form=form)
        else:
            file_names = generator(
                startDate, endDate, stationlist, user, HD_indicator, SP_indicator, root_path)
            session['id'] = file_names
            return redirect(url_for('main.display', startDate=startDate, endDate=endDate))

    if form.errors:
        # print(form.errors)
        flash("You must select a valid date range, in this format: 'YYYY-MM-DD'", "warning")
        form = LocationForm()
        return render_template('home.html', form=form)
    return render_template('home.html', form=form)


@main.route("/about")
def about():
    return render_template('about.html')


@main.route("/display/<string:startDate>/<string:endDate>", methods=['GET', 'POST'])
def display(startDate, endDate):

    root_path = os.path.dirname(current_app.instance_path) + '/'

    form = LocationForm()

    if form.validate_on_submit():

        stationlist = []

        request.form.getlist("")

        if(form.BV_checkbox.data):
            stationlist.append('bv')

        if(form.LN_checkbox.data):
            stationlist.append('ln')

        if(form.SM_checkbox.data):
            stationlist.append('sm')

        if(form.HD_checkbox.data):
            HD_indicator = True
        else:
            HD_indicator = False

        if(form.SP_checkbox.data):
            SP_indicator = True
        else:
            SP_indicator = False

        startDate = form.StartDate.data
        endDate = form.EndDate.data

        startDate = startDate.strftime('%Y-%m-%d')
        endDate = endDate.strftime('%Y-%m-%d')

        edge_date = '2017-07-18'

        time = datetime.now().strftime('%M%S%f')[:-4]
        todaysdate = datetime.now().strftime("%Y-%m-%d")

        user = todaysdate + time
        session['user'] = user

        if (todaysdate <= startDate):
            flash('Start date must be before today', 'warning')
            return render_template('home.html', form=form)

        if (todaysdate < endDate):
            flash('End date cannot be after today', 'warning')
            return render_template('home.html', form=form)

        if (endDate <= startDate):
            flash('Start date must be before end date', 'warning')
            return render_template('display.html', form=form)

        if not stationlist == []:
            if (startDate < edge_date):
                flash(
                    '07/18/2017 is the earliest date for delta-carbon data.', 'warning')
                return render_template('display.html', form=form)

        if (stationlist == []):

            if(HD_indicator):
                file_names = generator(
                    startDate, endDate, stationlist, user, HD_indicator, SP_indicator, root_path)
                session['id'] = file_names
                return redirect(url_for('main.display', startDate=startDate, endDate=endDate))
            else:
                flash(
                    "You must select at least one location, or heat-deficit", "warning")
                form = LocationForm()
                return render_template('display.html', form=form)
        else:
            file_names = generator(
                startDate, endDate, stationlist, user, HD_indicator, SP_indicator, root_path)
            session['id'] = file_names
            return redirect(url_for('main.display', startDate=startDate, endDate=endDate))

    if form.errors:
        # print(form.errors)
        flash("You must select a valid date range, in this format: 'YYYY-MM-DD'", "warning")
        form = LocationForm()
        return render_template('display.html', form=form)
    return render_template('display.html', form=form)

daqFlask/templates/about.html
{% extends  "layout.html" %}
{% block content %}

    <div class="content-section2">
        <h6><b>About the dashboard</b> </h6>

        The dashboard grew out of a <a href="https://deq.utah.gov/division-air-quality"> Utah Division of Air Quality (DAQ)</a>
        study designed to observe the effects of brown carbon (or delta carbon), an indicator of biomass burning, on local air quality.
        Results of this study can be found <a href=" {{ url_for('static', filename = '/papers/Glisson_DAQ_Report.pdf') }}"> here</a>. This study was conducted by three University of Utah <a href= "https://che.utah.edu"> Chemical Engineering </a> students,
        Jesse Glisson, Alex Robinson and Adrian Wride in partnership with <a href= "https://faculty.utah.edu/u0239821-KERRY_E._KELLY/hm/index.html"> Dr. Kerry Kelly</a>.<br> <br>

        At the conclusion of the study, Alex and Adrian continued work with Dr. Kelly to develop the dashboard.
        The idea behind the dashboard was to make the air quality data and resources collected (including methods developed) during the study easily accessible to anyone.
        <br>
        <br>
        <h6><b>Questions</b> </h6>
        If you have questions, comments or suggestions, please contact Dr. Kerry Kelly, Assistant Professor, Chemical Engineering, University of Utah.<br>
        email: kerry[dot]kelly[at]utah[dot]edu
    </div>
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
{% endblock content %}

daqFlask/templates/display.html
{% extends  "layout.html" %}
{% block content %}

    <div class = "content-section">
        <form method="POST" action="">
            {{form.hidden_tag()}}

            <div class="form-group" align="left">
                <b>Dates: </b> &nbsp;
                {{ form.StartDate.label(class="form-control-lable") }}
                {{ form.StartDate }}

                &nbsp;

                {{ form.EndDate.label(class="form-control-lable") }}
                {{ form.EndDate }}

            </div>

            <div class="form-group" align="left">
                <b>Locations: </b> &nbsp;

                {{ form.BV_checkbox}}
                {{ form.BV_checkbox.label(class="form-control-lable") }}
                &nbsp;
                {{ form.LN_checkbox}}
                {{ form.LN_checkbox.label(class="form-control-lable") }}
                &nbsp;
                {{ form.SM_checkbox}}
                {{ form.SM_checkbox.label(class="form-control-lable") }}
                <br>

            </div>

            <div class="form-group" align="left">
                <b>Options: </b> &nbsp;

                {{ form.HD_checkbox }}
                {{ form.HD_checkbox.label(class="form-control-lable") }}
                &nbsp;
                {{ form.SP_checkbox }}
                {{ form.SP_checkbox.label(class="form-control-lable") }}

            </div>

            <div class="form-group" align="left">
                <span align="left">
                    <a class="btn-sm btn-primary" href="/getzip">Download Data (.zip)</a>
                </span>

                <span style="float:right;">
                    {{form.submit(class="btn btn-outline-info")}}
                </span>
            </div>

        </form>

    </div>


    <div class = "content-section">
        {% for file in session['id']%}

            <div class="media">
                <img src="{{ url_for('static', filename = file ) }}" width="100%" height="auto">
            </div>

        {% endfor %}
    </div>
{% endblock content %}

daqFlask/templates/home.html
{% extends  "layout.html" %}
{% block content %}

<div class = "content-section">
    <form method="POST" action="">
        {{form.hidden_tag()}}

        <div class="form-group" align="left">
            <b>Dates: </b> &nbsp;
            {{ form.StartDate.label(class="form-control-lable") }}
            {{ form.StartDate }}

            &nbsp;

            {{ form.EndDate.label(class="form-control-lable") }}
            {{ form.EndDate }}

        </div>

        <div class="form-group" align="left">
            <b>Locations: </b> &nbsp;

            {{ form.BV_checkbox}}
            {{ form.BV_checkbox.label(class="form-control-lable") }}
            &nbsp;
            {{ form.LN_checkbox}}
            {{ form.LN_checkbox.label(class="form-control-lable") }}
            &nbsp;
            {{ form.SM_checkbox}}
            {{ form.SM_checkbox.label(class="form-control-lable") }}

        </div>

        <div class="form-group" align="left">
            <b>Options: </b> &nbsp;

            {{ form.HD_checkbox }}
            {{ form.HD_checkbox.label(class="form-control-lable") }}
            &nbsp;
            {{ form.SP_checkbox }}
            {{ form.SP_checkbox.label(class="form-control-lable") }}

            <span style="float:right;">
                {{form.submit(class="btn btn-xs btn-outline-info")}}
            </span>

        </div>


    </form>

</div>

<div class = "content-section">

    <h4><center><b>Welcome!</b></center></h4>
    <p>
    Thank you for visiting the University of Utah’s Aethalometer Dashboard.  We hope you find this little tool useful.
    </p>
</div>

<div class = "content-section">
    <h4><center><b>What’s on the dashboard?</b></center></h4> <br>

        <h5><b>Brown Carbon</b> </h5>

    <p>
        The brown carbon data comes from the <a href ="https://deq.utah.gov/"> Utah Division of Air Quality's </a> <a href = "https://mageesci.com/our-products/ae33/">seven-channel aethalometers </a> located in Bountiful, Lindon, and Smithfield, Utah. Brown carbon is an indicator of biomass combustion.  During the winter brown carbon can indicate cooking with wood or residential wood burning.  Because northern Utah experiences periodic episodes of particle pollution and heating with wood emits orders of magnitude more particle pollution than heating with natural gas, the state restricts woodburning during episodes of poor air quality.  Studying long-term trends in brown carbon can help understand the effectiveness of wood-burning control measures.  More information about the effects of burning wood and wood-burning restrictions can be found <a href = "https://deq.utah.gov/air-quality/wood-burn-program"> here </a>.
    </p>
        <h5><b>Heat Deficit</b> </h5>
    <p>
        Heat deficit is a measure of atmospheric stability, and heat deficits greater than four are indicative of a stable atmosphere, with larger values indicating a more stable atmosphere. Normally air temperature decreases with elevation, but sometimes, cold air becomes trapped in a valley by a layer of warmer air, and these stable-air events are known as "inversions" or cold air pools. In northern Utah, cold air pools are often associated with elevated levels of particle pollution.
    </p>

    <p>
        The heat deficit is calculated from rawinsonde data collected at the Salt Lake City airport and is available <a href = "http://weather.uwyo.edu/upperair/sounding.html">here</a> through the University of Wyoming.
    </p>

    <p>
        More information on heat deficit can be found in <a href=" {{ url_for('static', filename = 'papers/Whiteman_paper.pdf') }}"> Whiteman et al. 1998</a>, and the expression used to calculate the heat deficit can be found below:
    </p>

    <center>
        <img src="/static/img/equations/integral.jpeg" width="100%" height="100%">
    </center>

    </p>
        <h5><b>Air Quality Index (Day Type)</b> </h5>
    <p>

    <p>
        From the Utah Department of Environmental Quality: The air quality index (AQI) indicates the highest pollution level of a given day. Please visit https://air.utah.gov/forecast.php or https://slco.org/health/air-quality/wood-burning/ for more information.
    </p>

</div>

<div class = "content-section">

    <h4><center><b>FAQ</b></center></h4> <br>

      <h6> <b>Why consider brown carbon, burn conditions, and heat deficit together? </b></h6>

    <p>
    A number of factors affect an individual's choice to burn wood, including economics, temperature, and burn conditions. We plot these together to help understand these relationships and the effectiveness of burn restrictions. Note that each of the three locations has its own burn restrictions, so you must plot the data individually to see the burn conditions.
    </p>

      <h6><b>What date ranges can I query?</b> </h6>

    <p>
    Delta-carbon data exists after July 18, 2017 for Bountiful, September 5, 2018 for Smithfield and November 20, 2018 for Lindon. Heat-deficit data exists beginning January 1, 1973.
    </p>

<!--     <h6><b>How long will it take to generate and download data?</b> </h6>

    <p>
    Selecting a single month for all three stations takes approximately 5 seconds.
    Selecting longer time ranges and separate plots will result in longer wait times.
    </p> -->

    <h6><b>What if I keep getting an error when I query?</b> </h6>
    <p>
        It is possible that data is not available during the time period. Try searching a different time period. If you continue to receive errors, please reach out to us.
    </p>

</div>

{% endblock content %}

daqFlask/templates/layout.html
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Aethalometer Dashboard{{ title }}</title>
    {% else %}
        <title>Aethalometer Dashboard</title>
    {% endif %}

</head>

<body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">&nbsp; Aethalometer Dashboard</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home')}}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about')}}">About</a>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
      </div>
    </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

<footer>
          &nbsp;
          <a href="https://utah.edu"><img src="/static/img/logos/uofulogo.png" width="85" height="60"></a>
          &nbsp;
          &nbsp;
          &nbsp;
          &nbsp;
          &nbsp;
          &nbsp;
          <a href="https://deq.utah.gov/division-air-quality"><img src="/static/img/logos/daqlogo.png" width="171" height="60"></a>
          &nbsp;
          <small><br><br>&copy; Copyright {{ now.year }}, University of Utah and Utah Division of Air Quality</small>
</footer>

</html>